
//products data get

export const LOAD_PRODUCTS_DATA_START="LOAD_PRODUCTS_DATA_START"
export const LOAD_PRODUCTS_DATA_SUCCESS="LOAD_PRODUCTS_DATA_SUCCESS"
export const LOAD_PRODUCTS_DATA_ERROR="LOAD_PRODUCTS_DATA_ERROR"


export const EMAILANDPASSWORD_SIGNUP_START="EMAILANDPASSWORD_SIGNUP_START"
export const EMAILANDPASSWORD_SIGNUP_SUCCESS="EMAILANDPASSWORD_SIGNUP_SUCCESS"
export const EMAILANDPASSWORD_SIGNUP_ERROR="EMAILANDPASSWORD_SIGNUP_ERROR"


export const MOBILE_LOGIN_START="MOBILE_LOGIN_START"
export const MOBILE_LOGIN_SUCCESS="MOBILE_LOGIN_SUCCESS"
export const MOBILE_LOGIN_ERROR="MOBILE_LOGIN_ERROR"
export const RESET_MOBILE_DATA = "RESET_MOBILE_DATA"

export const GOOGLE_LOGIN_START="GOOGLE_LOGIN_START"
export const GOOGLE_LOGIN_SUCCESS="GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_ERROR="GOOGLE_LOGIN_ERROR"

export const FACEBOOK_LOGIN_START="FACEBOOK_LOGIN_START"
export const FACEBOOK_LOGIN_SUCCESS="FACEBOOK_LOGIN_SUCCESS"
export const FACEBOOK_LOGIN_ERROR="FACEBOOK_LOGIN_ERROR"


export const CART_POST_START = "CART_POST_START"
export const CART_POST_SUCCESS = "CART_POST_SUCCESS"
export const CART_POST_ERROR = "CART_POST_ERROR"

export const CART_LOAD_START = "CART_LOAD_START"
export const CART_LOAD_SUCCESS = "CART_LOAD_SUCCESS"
export const CART_LOAD_ERROR = "CART_LOAD_ERROR"

export const CART_DELETE_START = "CART_DELETE_START"
export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS"
export const CART_DELETE_ERROR = "CART_DELETE_ERROR"

export const CART_PUT_START = "CART_PUT_START"
export const CART_PUT_SUCCESS = "CART_PUT_SUCCESS"
export const CART_PUT_ERROR = "CART_PUT_ERROR"

export const WISHLIST_POST_START = "WISHLIST_POST_START"
export const WISHLIST_POST_SUCCESS = "WISHLIST_POST_SUCCESS"
export const WISHLIST_POST_ERROR = "WISHLIST_POST_ERROR"

export const WISHLIST_LOAD_START = "WISHLIST_LOAD_START"
export const WISHLIST_LOAD_SUCCESS = "WISHLIST_LOAD_SUCCESS"
export const WISHLIST_LOAD_ERROR = "WISHLIST_LOAD_ERROR"

export const WISHLIST_DELETE_START = "WISHLIST_DELETE_START"
export const WISHLIST_DELETE_SUCCESS = "WISHLIST_DELETE_SUCCESS"
export const WISHLIST_DELETE_ERROR = "WISHLIST_DELETE_ERROR"

export const CHECKOUT_POST_START = "CHECKOUT_POST_START"
export const CHECKOUT_POST_SUCCESS = "CHECKOUT_POST_SUCCESS"
export const CHECKOUT_POST_ERROR = "CHECKOUT_POST_ERROR"

export const CHECKOUT_LOAD_START = "CHECKOUT_LOAD_START"
export const CHECKOUT_LOAD_SUCCESS = "CHECKOUT_LOAD_SUCCESS"
export const CHECKOUT_LOAD_ERROR = "CHECKOUT_LOAD_ERROR"

export const CHECKOUT_DELETE_START = "CHECKOUT_DELETE_START"
export const CHECKOUT_DELETE_SUCCESS = "CHECKOUT_DELETE_SUCCESS"
export const CHECKOUT_DELETE_ERROR = "CHECKOUT_DELETE_ERROR"

export const ADDRESS_POST_START = "ADDRESS_POST_START"
export const ADDRESS_POST_SUCCESS = "ADDRESS_POST_SUCCESS"
export const ADDRESS_POST_ERROR = "ADDRESS_POST_ERROR"

export const ADDRESS_PUT_START = "ADDRESS_PUT_START"
export const ADDRESS_PUT_SUCCESS = "ADDRESS_PUT_SUCCESS"
export const ADDRESS_PUT_ERROR = "ADDRESS_PUT_ERROR"

export const ADDRESS_LOAD_START = "ADDRESS_LOAD_START"
export const ADDRESS_LOAD_SUCCESS = "ADDRESS_LOAD_SUCCESS"
export const ADDRESS_LOAD_ERROR = "ADDRESS_LOAD_ERROR"


export const ORDER_LOAD_START = "ORDER_LOAD_START"
export const ORDER_LOAD_SUCCESS = "ORDER_LOAD_SUCCESS"
export const ORDER_LOAD_ERROR = "ORDER_LOAD_ERROR"

export const PROFILE_LOAD_START = "PROFILE_LOAD_START"
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS"
export const PROFILE_LOAD_ERROR = "PROFILE_LOAD_ERROR"

export const PROFILE_PUT_START = "PROFILE_PUT_START"
export const PROFILE_PUT_SUCCESS = "PROFILE_PUT_SUCCESS"
export const PROFILE_PUT_ERROR = "PROFILE_PUT_ERROR"

export const RAZORPAY_ORDER_POST_START = "RAZORPAY_ORDER_POST_START"
export const RAZORPAY_ORDER_POST_SUCCESS = "RAZORPAY_ORDER_POST_SUCCESS"
export const RAZORPAY_ORDER_POST_ERROR = "RAZORPAY_ORDER_POST_ERROR"

export const RAZORPAY_ORDER_VALIDATE_POST_START = "RAZORPAY_ORDER_VALIDATE_POST_START"
export const RAZORPAY_ORDER_VALIDATE_POST_SUCCESS = "RAZORPAY_ORDER_VALIDATE_POST_SUCCESS"
export const RAZORPAY_ORDER_VALIDATE_POST_ERROR = "RAZORPAY_ORDER_VALIDATE_POST_ERROR"

export const ORDER_DELETE_START = "ORDER_DELETE_START"
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS"
export const ORDER_DELETE_ERROR = "ORDER_DELETE_ERROR"

export const ORDER_PATCH_START = "ORDER_PATCH_START"
export const ORDER_PATCH_SUCCESS = "ORDER_PATCH_SUCCESS"
export const ORDER_PATCH_ERROR = "ORDER_PATCH_ERROR"

export const SAVE_SUBSCRIPTION_POST_START = "SAVE_SUBSCRIPTION_POST_START"
export const SAVE_SUBSCRIPTION_POST_SUCCESS = "SAVE_SUBSCRIPTION_POST_SUCCESS"
export const SAVE_SUBSCRIPTION_POST_ERROR = "SAVE_SUBSCRIPTION_POST_ERROR"

export const SEND_NOTIFICATION_POST_START = "SEND_NOTIFICATION_POST_START"
export const SEND_NOTIFICATION_POST_SUCCESS = "SEND_NOTIFICATION_POST_SUCCESS"
export const SEND_NOTIFICATION_POST_ERROR = "SEND_NOTIFICATION_POST_ERROR"

export const ADMIN_LOGIN_START="ADMIN_LOGIN_START"
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_ERROR="ADMIN_LOGIN_ERROR"

export const CONTENT_LOAD_START = "CONTENT_LOAD_START"
export const CONTENT_LOAD_SUCCESS = "CONTENT_LOAD_SUCCESS"
export const CONTENT_LOAD_ERROR = "CONTENT_LOAD_ERROR"

export const INVOICE_POST_START = "INVOICE_POST_START"
export const INVOICE_POST_SUCCESS = "INVOICE_POST_SUCCESS"
export const INVOICE_POST_ERROR = "INVOICE_POST_ERROR"